### ISSUE TITLE
Фильтр по полям вложенных моделей

### ISSUE THREAD

**Issue by AleksandrPU** [kr-aleksey/PyOData1C#2]
Подготовил изменение в виде патча для добавления возможности использовать фильтр по полям вложенных моделей.
[add_filter_to_nested_model.txt](https://github.com/user-attachments/files/17983754/add_filter_to_nested_model.txt)

Для того, чтобы проходила проверка на существование поля нужно в модель добавить описание вложенного поля.
Например, для фильтра по полю _work_center_type_uid_1c_ вложенной модели _work_centers_ нужно добавить в исходную модель:
```Python
work_centers__work_center_type_uid_1c: str = None
```

**Comment by AleksandrPU** [comment]
Забыл написать, изменения нужно внести в odata.py.
Немного упростил код:
[odata.py.patch.txt](https://github.com/user-attachments/files/17987951/odata.py.patch.txt)

**Comment by AleksandrPU** [comment]
Добавил исключение полей с required=False из query-параметра $select:
[odata.py.patch.20241203.txt](https://github.com/user-attachments/files/17988290/odata.py.patch.20241203.txt)

**Comment by kr-aleksey** [comment]
Привет! Александр, спасибо за предложения по улучшению библиотеки. Давай попробуем работать через pull request. Так всем будет проще. Только раздели пожалуйста предложенный функционал по фильтрации и исключению полей в разные pull request. Еще предлагаю рассмотреть логику парсинга lookup немного по-другому. Оператор и аннотация не могут содержать '__'. Мы можем считать именем поля все что находится до оператора. Все операторы в Q._operators. Например, foo__bar__eq=5. Нашли оператор по индексу 2, значит имя поля 'foo__bar' (0 и 1 склеиваем). Если оператора нет, значит весь lookup является именем поля. Так мы парсим имя поля любой вложенности. Мне кажется, логика при таком подходе будет немного проще, а значит надежней.
До pull request прошу обязательно тестировать изменения Q не только опосредовано через ODataManager, но и непосредственно инстанцируя Q.  Необходимо убедиться, что все методы объекта Q (например __str__()) работают как ожидалось. Дело в том, что ODataManager использует только метод Q.build_expression(), и передает словарь field_mapping. Другие методы не передают field_mapping и в этой ситуации поведение может отличаться.

**Comment by AleksandrPU** [comment]
Создал pull request-ы:
[Фильтр по полям вложенных моделей](https://github.com/kr-aleksey/PyOData1C/pull/3)
[Исключение необязательных полей из query-параметра $select](https://github.com/kr-aleksey/PyOData1C/pull/4)
